config/routes.rb
Monepicerie::Application.routes.draw do

  root :to => 'static_pages#home'
  match '/', :to => 'static_pages#home'
  match '/home', :to => 'static_pages#home'
  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :savemoneys

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def help
    
  end

  def about
    
  end
  
  def contact
    
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div data-role="header">
	<h1><%=t :about_title %></h1>	
</div>

<div data-role="content">
	<p>
		<%=t :about_content %>
	</p>
</div>

app/views/static_pages/contact.html.erb
<div data-role="header">
	<h1><%=t :contact_h1 %></h1>	
</div>

<div data-role="content">
	<p>
		<%=t :contact_content %>
	</p>
</div>

app/views/static_pages/help.html.erb
<div data-role="header">
	<h1><%=t :help_title %></h1>	
</div>

<div data-role="content">
	<p>
		<%=t :help_content %>
	</p>
</div>

app/views/static_pages/home.html.erb
<div data-role="header">
	<h1><%=t :home_title %></h1>	
</div>

<div data-role="content">
	<ul data-role="listview">
		<li><%= link_to I18n.t(:url_home),    root_path    %></li>
		<li><%= link_to I18n.t(:url_help),    help_path    %></li>
		<% if signed_in? %>
			<li><%= link_to I18n.t(:users), users_path %></li>
			<li><%= link_to I18n.t(:url_contact), contact_path %></li>
			<li><%= link_to I18n.t(:url_edit_profile), edit_user_path(current_user) %></li>
			<li><%= link_to I18n.t(:url_sign_out), signout_path(current_user), :method => 'delete' %></li><br/>
		<% else %>
	  		<li><%= link_to I18n.t(:url_sign_in), signin_path %></li>
			<li><%= link_to I18n.t(:url_sign_up), signup_path %></li>
		<% end %>
	</ul>
	<%= render 'shared/save_money_button' %>
	<% if signed_in? %>
		<%#= render 'shared/micropost_form' %>
		<%#= render 'shared/feed' %>
		<%#= render 'shared/stats' %>
	<% end %>
</div>