config/routes.rb
Monepicerie::Application.routes.draw do

  root :to => 'static_pages#home'
  match '/', :to => 'static_pages#home'
  match '/home', :to => 'static_pages#home'
  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy', :via => :delete
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :savemoneys

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			<%= t('form_errors_count') %> <%= pluralize(object.errors.count, t('error')) %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<div>
	<h3><%= I18n.t(:micropost_feed) %></h3>
	<% if @feed_items.any? %>
		<%= I18n.t(:you_have) %> <%= @feed_items.count %> <%= I18n.t(:post) %> 
				 <%= link_to I18n.t(:click_here_to_see_them), current_user %>
	<% else %>
		<%= I18n.t(:you_have_zero_post) %>
	<% end %>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field" >
		<%= f.text_area :content, :cols => 50, :rows => 3, :placeholder => I18n.t(:compose_new_post) %>
	</div>
	<%= f.submit t(:create_post), :class => "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_save_money_button.html.erb
<%= form_for(:savemoney, :url => savemoneys_path, :remote => true) do |f| %>
	<%= f.submit I18n.t(:save_money_button), :class => "btn btn-large btn-primary" %>
<% end %>
<div id="save_money_result" class="save_money_result"></div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		<%= I18n.t(:following) %>
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		<%= I18n.t(:followers) %>
	</a>
</div>